### ISSUE TITLE
Extra containers in Upgrade request (cht-nginx, cht-couchdb)

### ISSUE THREAD

**Issue by Hareet** [medic/upgrade-service-kubernetes#10]
The upgrade service kubernetes receives a request which contains containers that are not present in medic-hosted environments. I just wanted to make sure this scenario was covered.

Two things that came to mind:
- We had initially decided to handle CouchDB upgrades in clustered environments at a later release for hosted projects. We could mix that in with a later upgrade-service-kubernetes release.
- We won't run cht-nginx in hosted, so the upgrade service container should skip over any containers not already present. We haven't solved how to add new services seamlessly across deployment scenarios (later release).

@henokgetachew @dianabarsan Thoughts?

**Comment by henokgetachew** [comment]
The upgrade service kubernetes has been made future proof in this sense. There is a test [here](https://github.com/medic/upgrade-service-kubernetes/blob/master/tests/e2e/api-interface.spec.ts#L71-L90) to make sure that's the case.

>We won't run cht-nginx in hosted, so the upgrade service container should skip over any containers not already present. We haven't solved how to add new services seamlessly across deployment scenarios (later release).

That's already the case. So I'm closing this ticket as taken care of.

**Comment by henokgetachew** [comment]
The idea right now is to just ignore containers that don't exist in the namespace.

**Comment by henokgetachew** [comment]
This has been taken care of. Tests also passing right now.
